import { BarChart3, Database, LockKeyhole } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { useAuth } from '@/src/auth/auth-provider';

export function LoginPage() {
  const { signIn } = useAuth();
  const local = import.meta.env.DEV && import.meta.env.VITE_CX_PDOH_DEMO_AUTH === 'true';
  const configured = Boolean(import.meta.env.VITE_CX_PDOH_LOGIN_URL) || local;
  return <main className="grid min-h-screen bg-slate-950 lg:grid-cols-[1.15fr_0.85fr]"><section className="relative hidden overflow-hidden p-12 lg:flex lg:flex-col lg:justify-between"><div className="absolute -left-40 top-1/3 size-[32rem] rounded-full bg-blue-600/25 blur-3xl" /><div className="relative flex items-center gap-3"><div className="grid size-11 place-items-center rounded-xl bg-blue-500 font-extrabold text-white">CX</div><div><p className="font-semibold text-white">PDOH Platform</p><p className="text-xs text-blue-200/60">Consulta operacional</p></div></div><div className="relative max-w-xl"><p className="text-sm font-bold uppercase tracking-[0.2em] text-blue-400">Dados processados · somente leitura</p><h1 className="mt-4 text-5xl font-bold leading-tight tracking-tight text-white">Execuções e validações.<br />Uma visão rastreável.</h1><p className="mt-5 text-lg text-slate-300">Acompanhe oportunidades, regras e identificadores registrados pelo PDOH_CX, sem alterar o processamento.</p></div><div className="relative grid grid-cols-2 gap-4 text-sm text-slate-300"><span className="flex gap-2"><Database className="size-5 text-blue-400" /> Dados via API</span><span className="flex gap-2"><BarChart3 className="size-5 text-blue-400" /> Indicadores reais</span></div></section><section className="flex items-center justify-center bg-slate-50 p-6"><Card className="w-full max-w-md shadow-2xl"><CardContent className="p-9"><p className="text-xs font-bold uppercase tracking-[0.18em] text-blue-600">Acesso PDOH_CX</p><h2 className="mt-2 text-3xl font-bold">Bem-vindo à consulta</h2><p className="mt-2 text-sm leading-relaxed text-slate-500">A interface usa a API de consulta. Credenciais do MySQL e token da API não são incluídos no navegador.</p><Button className="mt-8 w-full" disabled={!configured} onClick={signIn}>Entrar</Button>{local && <p className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs text-amber-800">Sessão local apenas para desenvolvimento. Não equivale à autenticação corporativa.</p>}{!configured && <p className="mt-4 flex gap-2 rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs text-amber-800"><LockKeyhole className="size-4 shrink-0" />Configure o login da aplicação hospedeira antes de publicar esta interface.</p>}</CardContent></Card></section></main>;
}
